#!/bin/bash
# This is will perform twitter_fetch,py on the twitter_users[] array. Add any number of twitter_users[NUMBER]="USER" lines below
# to archive additional accounts.

# --- twitter user list ---
twitter_users[0]="bruce_katz"
twitter_users[1]="sommermathis"
twitter_users[2]="dianalindindex"
twitter_users[3]="ccoletta"
twitter_users[4]="urbanophile"
twitter_users[5]="architwibe"
twitter_users[6]="archpaper"
twitter_users[7]="architectmag"
twitter_users[8]="PPS_Placemaking"
twitter_users[9]="SmartGrowthUSA"
twitter_users[10]="GOVERNING"
twitter_users[11]="modeld"
twitter_users[12]="The_Suburbanist"
twitter_users[13]="ttpolitic"
twitter_users[14]="UrbanFarmMag"
twitter_users[15]="NextAmCity"
twitter_users[16]="PatternCities"
twitter_users[17]="CityJournal"
twitter_users[18]="MetropolisMag"
twitter_users[19]="dwell"
twitter_users[20]="planetizen"
twitter_users[21]="AtlanticCities"
twitter_users[22]="SPUR_Urbanist"
twitter_users[23]="StreetsblogNet"
twitter_users[24]="urbdispatch"
twitter_users[25]="MarketUrbanism"
twitter_users[26]="the_curioscity"
twitter_users[27]="BXP_NYC"
twitter_users[28]="douglasdevdc"
twitter_users[29]="GNOinc"
twitter_users[30]="srogel"
twitter_users[31]="seanrobbinsPDX"
twitter_users[32]="MitchLandrieu"
twitter_users[33]="mayormcginn"
twitter_users[34]="mayortommenino"
twitter_users[35]="MayorSRB"
twitter_users[36]="MayorACWharton"
twitter_users[37]="mayordavebing"
twitter_users[38]="anthonyfoxx"
twitter_users[39]="Betsy_Price"
twitter_users[40]="MichaelBColeman"
twitter_users[41]="MayorAlvinBrown"
twitter_users[42]="Mike_Rawlings"
twitter_users[43]="MayorSanders"
twitter_users[44]="MayorStanton"
twitter_users[45]="MayorHancock"
twitter_users[46]="mayorvincegray"
twitter_users[47]="JulianCastro"
twitter_users[48]="mayoredlee"
twitter_users[49]="MayorBallard"
twitter_users[50]="anniseparker"
twitter_users[51]="MayorSamAdams"
twitter_users[52]="KasimReed"
twitter_users[53]="MikeBloomberg"
twitter_users[54]="Michael_Nutter"
twitter_users[55]="MayorRTRybak"
twitter_users[56]="CoryBooker"
twitter_users[57]="RahmEmanuel"
twitter_users[58]="LAMayorsOffice"
twitter_users[59]="urbaninstitute"
twitter_users[60]="nycfuture"
twitter_users[61]="UrbanLandInst"
twitter_users[62]="urbanplanning"
twitter_users[63]="bruce_katz"
twitter_users[64]="BrookingsMetro"
twitter_users[65]="MarkMuro1"
twitter_users[66]="amy_liuw"
twitter_users[67]="urbanophile"
twitter_users[68]="D3detroit"
twitter_users[69]="KennyMcDon"
twitter_users[70]="Richard_Florida"
twitter_users[71]="seanrobbinsPDX"
twitter_users[72]="DPGilmartin"

# --- execute twitter_fetch.py ---
for twitter_user in ${twitter_users[*]}
do
	echo "Getting tweets for user $twitter_user"
	python twitter_fetch.py $twitter_user
	echo "Done."
	echo ""
done
